export const cityToTimezoneMap = {
        "london": { "timezone": "Europe/London", "displayName": "London, UK" },
        "paris": { "timezone": "Europe/Paris", "displayName": "Paris, France" },
        "new york": { "timezone": "America/New_York", "displayName": "New York, USA" },
        "los angeles": { "timezone": "America/Los_Angeles", "displayName": "Los Angeles, USA" },
        "tokyo": { "timezone": "Asia/Tokyo", "displayName": "Tokyo, Japan" },
        "sydney": { "timezone": "Australia/Sydney", "displayName": "Sydney, Australia" },
        "dubai": { "timezone": "Asia/Dubai", "displayName": "Dubai, UAE" },
        "berlin": { "timezone": "Europe/Berlin", "displayName": "Berlin, Germany" },
        "rome": { "timezone": "Europe/Rome", "displayName": "Rome, Italy" },
        "madrid": { "timezone": "Europe/Madrid", "displayName": "Madrid, Spain" },
        "moscow": { "timezone": "Europe/Moscow", "displayName": "Moscow, Russia" },
        "beijing": { "timezone": "Asia/Shanghai", "displayName": "Beijing, China" },
        "shanghai": { "timezone": "Asia/Shanghai", "displayName": "Shanghai, China" },
        "delhi": { "timezone": "Asia/Kolkata", "displayName": "Delhi, India" },
        "mumbai": { "timezone": "Asia/Kolkata", "displayName": "Mumbai, India" },
        "singapore": { "timezone": "Asia/Singapore", "displayName": "Singapore, Singapore" },
        "hong kong": { "timezone": "Asia/Hong_Kong", "displayName": "Hong Kong, China" },
        "cape town": { "timezone": "Africa/Johannesburg", "displayName": "Cape Town, South Africa" },
        "johannesburg": { "timezone": "Africa/Johannesburg", "displayName": "Johannesburg, South Africa" },
        "rio de janeiro": { "timezone": "America/Sao_Paulo", "displayName": "Rio de Janeiro, Brazil" },
        "buenos aires": { "timezone": "America/Argentina/Buenos_Aires", "displayName": "Buenos Aires, Argentina" },
        "mexico": { "timezone": "America/Mexico_City", "displayName": "Mexico City, Mexico" },
        "toronto": { "timezone": "America/Toronto", "displayName": "Toronto, ON, Canada" },
        "montréal": { "timezone": "America/Montreal", "displayName": "Montréal, QC, Canada" },
        "québec": { "timezone": "America/Montreal", "displayName": "Québec, QC, Canada" },
        "ottawa": { "timezone": "America/Toronto", "displayName": "Ottawa, ON, Canada" },
        "vancouver": { "timezone": "America/Vancouver", "displayName": "Vancouver, BC, Canada" },
        "sao paulo": { "timezone": "America/Sao_Paulo", "displayName": "Sao Paulo, Brazil" },
        "cairo": { "timezone": "Africa/Cairo", "displayName": "Cairo, Egypt" },
        "istanbul": { "timezone": "Europe/Istanbul", "displayName": "Istanbul, Turkey" },
        "bangkok": { "timezone": "Asia/Bangkok", "displayName": "Bangkok, Thailand" },
        "jakarta": { "timezone": "Asia/Jakarta", "displayName": "Jakarta, Indonesia" },
        "manila": { "timezone": "Asia/Manila", "displayName": "Manila, Philippines" },
        "auckland": { "timezone": "Pacific/Auckland", "displayName": "Auckland, New Zealand" },
        "washington": { "timezone": "America/New_York", "displayName": "Washington D.C., USA" },
        "bruxelles": { "timezone": "Europe/Brussels", "displayName": "Bruxelles, Belgium" },
        "rabat": { "timezone": "Africa/Casablanca", "displayName": "Rabat, Morocco" },
        "amsterdam": { "timezone": "Europe/Amsterdam", "displayName": "Amsterdam, Netherlands" },
        "dublin": { "timezone": "Europe/Dublin", "displayName": "Dublin, Ireland" },
        "lisbon": { "timezone": "Europe/Lisbon", "displayName": "Lisbon, Portugal" },
        "vienna": { "timezone": "Europe/Vienna", "displayName": "Vienna, Austria" },
        "prague": { "timezone": "Europe/Prague", "displayName": "Prague, Czech Republic" },
        "warsaw": { "timezone": "Europe/Warsaw", "displayName": "Warsaw, Poland" },
        "athens": { "timezone": "Europe/Athens", "displayName": "Athens, Greece" },
        "helsinki": { "timezone": "Europe/Helsinki", "displayName": "Helsinki, Finland" },
        "stockholm": { "timezone": "Europe/Stockholm", "displayName": "Stockholm, Sweden" },
        "oslo": { "timezone": "Europe/Oslo", "displayName": "Oslo, Norway" },
        "copenhagen": { "timezone": "Europe/Copenhagen", "displayName": "Copenhagen, Denmark" },
        "edinburgh": { "timezone": "Europe/London", "displayName": "Edinburgh, UK" },
        "chicago": { "timezone": "America/Chicago", "displayName": "Chicago, USA" },
        "denver": { "timezone": "America/Denver", "displayName": "Denver, USA" },
        "phoenix": { "timezone": "America/Phoenix", "displayName": "Phoenix, USA" },
        "anchorage": { "timezone": "America/Anchorage", "displayName": "Anchorage, USA" },
        "honolulu": { "timezone": "Pacific/Honolulu", "displayName": "Honolulu, USA" },
        "bogota": { "timezone": "America/Bogota", "displayName": "Bogota, Colombia" },
        "lima": { "timezone": "America/Lima", "displayName": "Lima, Peru" },
        "santiago": { "timezone": "America/Santiago", "displayName": "Santiago, Chile" },
        "caracas": { "timezone": "America/Caracas", "displayName": "Caracas, Venezuela" },
        "lagos": { "timezone": "Africa/Lagos", "displayName": "Lagos, Nigeria" },
        "nairobi": { "timezone": "Africa/Nairobi", "displayName": "Nairobi, Kenya" },
        "riyadh": { "timezone": "Asia/Riyadh", "displayName": "Riyadh, Saudi Arabia" },
        "jerusalem": { "timezone": "Asia/Jerusalem", "displayName": "Jerusalem, Israel" },
        "seoul": { "timezone": "Asia/Seoul", "displayName": "Seoul, South Korea" },
        "kuala lumpur": { "timezone": "Asia/Kuala_Lumpur", "displayName": "Kuala Lumpur, Malaysia" },
        "ho chi minh city": { "timezone": "Asia/Ho_Chi_Minh", "displayName": "Ho Chi Minh City, Vietnam" },
        "perth": { "timezone": "Australia/Perth", "displayName": "Perth, Australia" },
        "brisbane": { "timezone": "Australia/Brisbane", "displayName": "Brisbane, Australia" },
        "adelaide": { "timezone": "Australia/Adelaide", "displayName": "Adelaide, Australia" },
        "wellington": { "timezone": "Pacific/Auckland", "displayName": "Wellington, New Zealand" },
        "canberra": { "timezone": "Australia/Sydney", "displayName": "Canberra, Australia" },
        "brasilia": { "timezone": "America/Sao_Paulo", "displayName": "Brasilia, Brazil" },
        "new delhi": { "timezone": "Asia/Kolkata", "displayName": "New Delhi, India" },
        "abuja": { "timezone": "Africa/Lagos", "displayName": "Abuja, Nigeria" },
        "algiers": { "timezone": "Africa/Algiers", "displayName": "Algiers, Algeria" },
        "tripoli": { "timezone": "Africa/Tripoli", "displayName": "Tripoli, Libya" },
        "tunis": { "timezone": "Africa/Tunis", "displayName": "Tunis, Tunisia" },
        "khartoum": { "timezone": "Africa/Khartoum", "displayName": "Khartoum, Sudan" },
        "addis ababa": { "timezone": "Africa/Addis_Ababa", "displayName": "Addis Ababa, Ethiopia" },
        "mogadishu": { "timezone": "Africa/Mogadishu", "displayName": "Mogadishu, Somalia" },
        "djibouti": { "timezone": "Africa/Djibouti", "displayName": "Djibouti, Djibouti" },
        "asmara": { "timezone": "Africa/Asmara", "displayName": "Asmara, Eritrea" },
        "doha": { "timezone": "Asia/Qatar", "displayName": "Doha, Qatar" },
        "manama": { "timezone": "Asia/Bahrain", "displayName": "Manama, Bahrain" },
        "kuwait city": { "timezone": "Asia/Kuwait", "displayName": "Kuwait City, Kuwait" },
        "abu dhabi": { "timezone": "Asia/Dubai", "displayName": "Abu Dhabi, UAE" },
        "muscat": { "timezone": "Asia/Muscat", "displayName": "Muscat, Oman" },
        "sana'a": { "timezone": "Asia/Aden", "displayName": "Sana'a, Yemen" },
        "baku": { "timezone": "Asia/Baku", "displayName": "Baku, Azerbaijan" },
        "tbilisi": { "timezone": "Asia/Tbilisi", "displayName": "Tbilisi, Georgia" },
        "yerevan": { "timezone": "Asia/Yerevan", "displayName": "Yerevan, Armenia" },
        "astana": { "timezone": "Asia/Almaty", "displayName": "Astana, Kazakhstan" },
        "tashkent": { "timezone": "Asia/Tashkent", "displayName": "Tashkent, Uzbekistan" },
        "bishkek": { "timezone": "Asia/Bishkek", "displayName": "Bishkek, Kyrgyzstan" },
        "dushanbe": { "timezone": "Asia/Dushanbe", "displayName": "Dushanbe, Tajikistan" },
        "ashgabat": { "timezone": "Asia/Ashgabat", "displayName": "Ashgabat, Turkmenistan" },
        "kathmandu": { "timezone": "Asia/Kathmandu", "displayName": "Kathmandu, Nepal" },
        "thimphu": { "timezone": "Asia/Thimphu", "displayName": "Thimphu, Bhutan" },
        "dhaka": { "timezone": "Asia/Dhaka", "displayName": "Dhaka, Bangladesh" },
        "colombo": { "timezone": "Asia/Colombo", "displayName": "Colombo, Sri Lanka" },
        "male": { "timezone": "Indian/Maldives", "displayName": "Malé, Maldives" },
        "ulaanbaatar": { "timezone": "Asia/Ulaanbaatar", "displayName": "Ulaanbaatar, Mongolia" },
        "pyongyang": { "timezone": "Asia/Pyongyang", "displayName": "Pyongyang, North Korea" },
        "vientiane": { "timezone": "Asia/Vientiane", "displayName": "Vientiane, Laos" },
        "phnom penh": { "timezone": "Asia/Phnom_Penh", "displayName": "Phnom Penh, Cambodia" },
        "naypyidaw": { "timezone": "Asia/Yangon", "displayName": "Naypyidaw, Myanmar" },
        "bandar seri begawan": { "timezone": "Asia/Brunei", "displayName": "Bandar Seri Begawan, Brunei" },
        "dili": { "timezone": "Asia/Dili", "displayName": "Dili, Timor-Leste" },
        "port moresby": { "timezone": "Pacific/Port_Moresby", "displayName": "Port Moresby, Papua New Guinea" },
        "honiara": { "timezone": "Pacific/Guadalcanal", "displayName": "Honiara, Solomon Islands" },
        "suva": { "timezone": "Pacific/Fiji", "displayName": "Suva, Fiji" },
        "nukuʻalofa": { "timezone": "Pacific/Tongatapu", "displayName": "Nukuʻalofa, Tonga" },
        "apia": { "timezone": "Pacific/Apia", "displayName": "Apia, Samoa" },
        "palikir": { "timezone": "Pacific/Pohnpei", "displayName": "Palikir, Micronesia" },
        "majuro": { "timezone": "Pacific/Majuro", "displayName": "Majuro, Marshall Islands" },
        "tarawa": { "timezone": "Pacific/Tarawa", "displayName": "Tarawa, Kiribati" },
        "yaren": { "timezone": "Pacific/Nauru", "displayName": "Yaren, Nauru" },
        "funafuti": { "timezone": "Pacific/Funafuti", "displayName": "Funafuti, Tuvalu" },
        "alofi": { "timezone": "Pacific/Niue", "displayName": "Alofi, Niue" },
        "hagåtña": { "timezone": "Pacific/Guam", "displayName": "Hagåtña, Guam" },
        "saipan": { "timezone": "Pacific/Saipan", "displayName": "Saipan, Northern Mariana Islands" },
        "pago pago": { "timezone": "Pacific/Pago_Pago", "displayName": "Pago Pago, American Samoa" },
        "nouméa": { "timezone": "Pacific/Noumea", "displayName": "Nouméa, New Caledonia" },
        "papeete": { "timezone": "Pacific/Tahiti", "displayName": "Papeete, French Polynesia" },
        "adamstown": { "timezone": "Pacific/Pitcairn", "displayName": "Adamstown, Pitcairn Islands" },
        "fakaofo": { "timezone": "Pacific/Fakaofo", "displayName": "Fakaofo, Tokelau" },
        "jamestown": { "timezone": "Atlantic/St_Helena", "displayName": "Jamestown, Saint Helena" },
        "stanley": { "timezone": "Atlantic/Stanley", "displayName": "Stanley, Falkland Islands" },
        "george town": { "timezone": "America/Cayman", "displayName": "George Town, Cayman Islands" },
        "road town": { "timezone": "America/Tortola", "displayName": "Road Town, British Virgin Islands" },
        "basseterre": { "timezone": "America/St_Kitts", "displayName": "Basseterre, Saint Kitts and Nevis" },
        "castries": { "timezone": "America/St_Lucia", "displayName": "Castries, Saint Lucia" },
        "kingstown": { "timezone": "America/St_Vincent", "displayName": "Kingstown, Saint Vincent and the Grenadines" },
        "st. john's": { "timezone": "America/Antigua", "displayName": "St. John's, Antigua and Barbuda" },
        "roseau": { "timezone": "America/Dominica", "displayName": "Roseau, Dominica" },
        "bridgetown": { "timezone": "America/Barbados", "displayName": "Bridgetown, Barbados" },
        "port of spain": { "timezone": "America/Port_of_Spain", "displayName": "Port of Spain, Trinidad and Tobago" },
        "paramaribo": { "timezone": "America/Paramaribo", "displayName": "Paramaribo, Suriname" },
        "georgetown": { "timezone": "America/Guyana", "displayName": "Georgetown, Guyana" },
        "cayenne": { "timezone": "America/Cayenne", "displayName": "Cayenne, French Guiana" },
        "panama city": { "timezone": "America/Panama", "displayName": "Panama City, Panama" },
        "san jose": { "timezone": "America/Costa_Rica", "displayName": "San Jose, Costa Rica" },
        "managua": { "timezone": "America/Managua", "displayName": "Managua, Nicaragua" },
        "tegucigalpa": { "timezone": "America/Tegucigalpa", "displayName": "Tegucigalpa, Honduras" },
        "san salvador": { "timezone": "America/El_Salvador", "displayName": "San Salvador, El Salvador" },
        "guatemala city": { "timezone": "America/Guatemala", "displayName": "Guatemala City, Guatemala" },
        "belmopan": { "timezone": "America/Belize", "displayName": "Belmopan, Belize" },
        "nassau": { "timezone": "America/Nassau", "displayName": "Nassau, Bahamas" },
        "havana": { "timezone": "America/Havana", "displayName": "Havana, Cuba" },
        "port-au-prince": { "timezone": "America/Port-au-Prince", "displayName": "Port-au-Prince, Haiti" },
        "santo domingo": { "timezone": "America/Santo_Domingo", "displayName": "Santo Domingo, Dominican Republic" },
        "kingston": { "timezone": "America/Jamaica", "displayName": "Kingston, Jamaica" },
        "reykjavik": { "timezone": "Atlantic/Reykjavik", "displayName": "Reykjavik, Iceland" },
        "bern": { "timezone": "Europe/Zurich", "displayName": "Bern, Switzerland" },
        "budapest": { "timezone": "Europe/Budapest", "displayName": "Budapest, Hungary" },
        "bucharest": { "timezone": "Europe/Bucharest", "displayName": "Bucharest, Romania" },
        "sofia": { "timezone": "Europe/Sofia", "displayName": "Sofia, Bulgaria" },
        "belgrade": { "timezone": "Europe/Belgrade", "displayName": "Belgrade, Serbia" },
        "zagreb": { "timezone": "Europe/Zagreb", "displayName": "Zagreb, Croatia" },
        "ljubljana": { "timezone": "Europe/Ljubljana", "displayName": "Ljubljana, Slovenia" },
        "sarajevo": { "timezone": "Europe/Sarajevo", "displayName": "Sarajevo, Bosnia and Herzegovina" },
        "tirana": { "timezone": "Europe/Tirane", "displayName": "Tirana, Albania" },
        "skopje": { "timezone": "Europe/Skopje", "displayName": "Skopje, North Macedonia" },
        "podgorica": { "timezone": "Europe/Podgorica", "displayName": "Podgorica, Montenegro" },
        "chișinău": { "timezone": "Europe/Chisinau", "displayName": "Chișinău, Moldova" },
        "kyiv": { "timezone": "Europe/Kyiv", "displayName": "Kyiv, Ukraine" },
        "minsk": { "timezone": "Europe/Minsk", "displayName": "Minsk, Belarus" },
        "riga": { "timezone": "Europe/Riga", "displayName": "Riga, Latvia" },
        "vilnius": { "timezone": "Europe/Vilnius", "displayName": "Vilnius, Lithuania" },
        "tallinn": { "timezone": "Europe/Tallinn", "displayName": "Tallinn, Estonia" },
        "valletta": { "timezone": "Europe/Malta", "displayName": "Valletta, Malta" },
        "nicosia": { "timezone": "Asia/Nicosia", "displayName": "Nicosia, Cyprus" },
        "beirut": { "timezone": "Asia/Beirut", "displayName": "Beirut, Lebanon" },
        "damascus": { "timezone": "Asia/Damascus", "displayName": "Damascus, Syria" },
        "baghdad": { "timezone": "Asia/Baghdad", "displayName": "Baghdad, Iraq" },
        "tehran": { "timezone": "Asia/Tehran", "displayName": "Tehran, Iran" },
        "kabul": { "timezone": "Asia/Kabul", "displayName": "Kabul, Afghanistan" },
        "islamabad": { "timezone": "Asia/Karachi", "displayName": "Islamabad, Pakistan" },
        "ulan bator": { "timezone": "Asia/Ulaanbaatar", "displayName": "Ulaanbaatar, Mongolia" },
        "st. john's": { "timezone": "America/St_Johns", "displayName": "St. John's, NL, Canada" },
        "charlottetown": { "timezone": "America/Halifax", "displayName": "Charlottetown, PE, Canada" },
        "halifax": { "timezone": "America/Halifax", "displayName": "Halifax, NS, Canada" },
        "fredericton": { "timezone": "America/Moncton", "displayName": "Fredericton, NB, Canada" },
        "winnipeg": { "timezone": "America/Winnipeg", "displayName": "Winnipeg, MB, Canada" },
        "regina": { "timezone": "America/Regina", "displayName": "Regina, SK, Canada" },
        "edmonton": { "timezone": "America/Edmonton", "displayName": "Edmonton, AB, Canada" },
        "calgary": { "timezone": "America/Edmonton", "displayName": "Calgary, AB, Canada" },
        "victoria": { "timezone": "America/Vancouver", "displayName": "Victoria, BC, Canada" },
        "yellowknife": { "timezone": "America/Yellowknife", "displayName": "Yellowknife, NT, Canada" },
        "whitehorse": { "timezone": "America/Whitehorse", "displayName": "Whitehorse, YT, Canada" },
        "iqaluit": { "timezone": "America/Iqaluit", "displayName": "Iqaluit, NU, Canada" },
        "seattle": { "timezone": "America/Los_Angeles", "displayName": "Seattle, WA, USA" },
        "san francisco": { "timezone": "America/Los_Angeles", "displayName": "San Francisco, CA, USA" },
        "houston": { "timezone": "America/Chicago", "displayName": "Houston, TX, USA" },
        "miami": { "timezone": "America/New_York", "displayName": "Miami, FL, USA" },
        "philadelphia": { "timezone": "America/New_York", "displayName": "Philadelphia, PA, USA" },
        "detroit": { "timezone": "America/Detroit", "displayName": "Detroit, MI, USA" },
        "boston": { "timezone": "America/New_York", "displayName": "Boston, MA, USA" },
        "atlanta": { "timezone": "America/New_York", "displayName": "Atlanta, GA, USA" },
        "dallas": { "timezone": "America/Chicago", "displayName": "Dallas, TX, USA" },
        "salt lake city": { "timezone": "America/Denver", "displayName": "Salt Lake City, UT, USA" },
        "las vegas": { "timezone": "America/Los_Angeles", "displayName": "Las Vegas, NV, USA" },
        "portland": { "timezone": "America/Los_Angeles", "displayName": "Portland, OR, USA" },
        "albuquerque": { "timezone": "America/Denver", "displayName": "Albuquerque, NM, USA" },
        "omaha": { "timezone": "America/Chicago", "displayName": "Omaha, NE, USA" },
        "nashville": { "timezone": "America/Chicago", "displayName": "Nashville, TN, USA" },
        "new orleans": { "timezone": "America/Chicago", "displayName": "New Orleans, LA, USA" },
        "minneapolis": { "timezone": "America/Chicago", "displayName": "Minneapolis, MN, USA" },
        "indianapolis": { "timezone": "America/Indianapolis", "displayName": "Indianapolis, IN, USA" },
        "cleveland": { "timezone": "America/New_York", "displayName": "Cleveland, OH, USA" },
        "baltimore": { "timezone": "America/New_York", "displayName": "Baltimore, MD, USA" },
        "charlotte": { "timezone": "America/New_York", "displayName": "Charlotte, NC, USA" },
        "columbus": { "timezone": "America/New_York", "displayName": "Columbus, OH, USA" },
        "milwaukee": { "timezone": "America/Chicago", "displayName": "Milwaukee, WI, USA" },
        "san antonio": { "timezone": "America/Chicago", "displayName": "San Antonio, TX, USA" },
        "fairbanks": { "timezone": "America/Anchorage", "displayName": "Fairbanks, AK, USA" },
        "honolulu": { "timezone": "Pacific/Honolulu", "displayName": "Honolulu, HI, USA" },
        "punta cana": { "timezone": "America/Santo_Domingo", "displayName": "Punta Cana, Dominican Republic" },
        "puerto plata": { "timezone": "America/Santo_Domingo", "displayName": "Puerto Plata, Dominican Republic" },
        "andorra la vella": { "timezone": "Europe/Andorra", "displayName": "Andorra la Vella, Andorra" },
        "luanda": { "timezone": "Africa/Luanda", "displayName": "Luanda, Angola" },
        "porto-novo": { "timezone": "Africa/Porto-Novo", "displayName": "Porto-Novo, Benin" },
        "la paz": { "timezone": "America/La_Paz", "displayName": "La Paz, Bolivia" },
        "sucre": { "timezone": "America/La_Paz", "displayName": "Sucre, Bolivia" },
        "gaborone": { "timezone": "Africa/Gaborone", "displayName": "Gaborone, Botswana" },
        "ouagadougou": { "timezone": "Africa/Ouagadougou", "displayName": "Ouagadougou, Burkina Faso" },
        "gitega": { "timezone": "Africa/Bujumbura", "displayName": "Gitega, Burundi" },
        "yaounde": { "timezone": "Africa/Douala", "displayName": "Yaounde, Cameroon" },
        "praia": { "timezone": "Atlantic/Cape_Verde", "displayName": "Praia, Cape Verde" },
        "bangui": { "timezone": "Africa/Bangui", "displayName": "Bangui, Central African Republic" },
        "n'djamena": { "timezone": "Africa/Ndjamena", "displayName": "N'Djamena, Chad" },
        "moroni": { "timezone": "Indian/Comoro", "displayName": "Moroni, Comoros" },
        "kinshasa": { "timezone": "Africa/Kinshasa", "displayName": "Kinshasa, DR Congo" },
        "brazzaville": { "timezone": "Africa/Brazzaville", "displayName": "Brazzaville, Rep. of the Congo" },
        "yamoussoukro": { "timezone": "Africa/Abidjan", "displayName": "Yamoussoukro, Côte d'Ivoire" },
        "quito": { "timezone": "America/Guayaquil", "displayName": "Quito, Ecuador" },
        "malabo": { "timezone": "Africa/Malabo", "displayName": "Malabo, Equatorial Guinea" },
        "mbabane": { "timezone": "Africa/Mbabane", "displayName": "Mbabane, Eswatini" },
        "lobamba": { "timezone": "Africa/Mbabane", "displayName": "Lobamba, Eswatini" },
        "libreville": { "timezone": "Africa/Libreville", "displayName": "Libreville, Gabon" },
        "banjul": { "timezone": "Africa/Banjul", "displayName": "Banjul, Gambia" },
        "accra": { "timezone": "Africa/Accra", "displayName": "Accra, Ghana" },
        "saint george's": { "timezone": "America/Grenada", "displayName": "Saint George's, Grenada" },
        "conakry": { "timezone": "Africa/Conakry", "displayName": "Conakry, Guinea" },
        "bissau": { "timezone": "Africa/Bissau", "displayName": "Bissau, Guinea-Bissau" },
        "amman": { "timezone": "Asia/Amman", "displayName": "Amman, Jordan" },
        "prishtina": { "timezone": "Europe/Belgrade", "displayName": "Prishtina, Kosovo" },
        "maseru": { "timezone": "Africa/Maseru", "displayName": "Maseru, Lesotho" },
        "monrovia": { "timezone": "Africa/Monrovia", "displayName": "Monrovia, Liberia" },
        "vaduz": { "timezone": "Europe/Vaduz", "displayName": "Vaduz, Liechtenstein" },
        "luxembourg city": { "timezone": "Europe/Luxembourg", "displayName": "Luxembourg City, Luxembourg" },
        "antananarivo": { "timezone": "Indian/Antananarivo", "displayName": "Antananarivo, Madagascar" },
        "lilongwe": { "timezone": "Africa/Blantyre", "displayName": "Lilongwe, Malawi" },
        "bamako": { "timezone": "Africa/Bamako", "displayName": "Bamako, Mali" },
        "nouakchott": { "timezone": "Africa/Nouakchott", "displayName": "Nouakchott, Mauritania" },
        "port louis": { "timezone": "Indian/Mauritius", "displayName": "Port Louis, Mauritius" },
        "maputo": { "timezone": "Africa/Maputo", "displayName": "Maputo, Mozambique" },
        "windhoek": { "timezone": "Africa/Windhoek", "displayName": "Windhoek, Namibia" },
        "niamey": { "timezone": "Africa/Niamey", "displayName": "Niamey, Niger" },
        "melekeok": { "timezone": "Pacific/Palau", "displayName": "Melekeok, Palau" },
        "asuncion": { "timezone": "America/Asuncion", "displayName": "Asuncion, Paraguay" },
        "kigali": { "timezone": "Africa/Kigali", "displayName": "Kigali, Rwanda" },
        "sao tome": { "timezone": "Africa/Sao_Tome", "displayName": "Sao Tome, Sao Tome and Principe" },
        "dakar": { "timezone": "Africa/Dakar", "displayName": "Dakar, Senegal" },
        "victoria (seychelles)": { "timezone": "Indian/Mahe", "displayName": "Victoria, Seychelles" },
        "freetown": { "timezone": "Africa/Freetown", "displayName": "Freetown, Sierra Leone" },
        "bratislava": { "timezone": "Europe/Bratislava", "displayName": "Bratislava, Slovakia" },
        "juba": { "timezone": "Africa/Juba", "displayName": "Juba, South Sudan" },
        "dodoma": { "timezone": "Africa/Dar_es_Salaam", "displayName": "Dodoma, Tanzania" },
        "lome": { "timezone": "Africa/Lome", "displayName": "Lome, Togo" },
        "ankara": { "timezone": "Europe/Istanbul", "displayName": "Ankara, Turkey" },
        "kampala": { "timezone": "Africa/Kampala", "displayName": "Kampala, Uganda" },
        "montevideo": { "timezone": "America/Montevideo", "displayName": "Montevideo, Uruguay" },
        "port vila": { "timezone": "Pacific/Port_Vila", "displayName": "Port Vila, Vanuatu" },
        "vatican city": { "timezone": "Europe/Vatican", "displayName": "Vatican City, Vatican City" },
        "hanoi": { "timezone": "Asia/Ho_Chi_Minh", "displayName": "Hanoi, Vietnam" },
        "lusaka": { "timezone": "Africa/Lusaka", "displayName": "Lusaka, Zambia" },
        "harare": { "timezone": "Africa/Harare", "displayName": "Harare, Zimbabwe" },
        "king edward point": { "timezone": "Atlantic/South_Georgia", "displayName": "King Edward Point, South Georgia and the South Sandwich Islands" },
        "nuuk": { "timezone": "America/Godthab", "displayName": "Nuuk, Greenland" },
        "longyearbyen": { "timezone": "Arctic/Longyearbyen", "displayName": "Longyearbyen, Svalbard and Jan Mayen" },
        "flying fish cove": { "timezone": "Indian/Christmas", "displayName": "Flying Fish Cove, Christmas Island" },
        "west island": { "timezone": "Indian/Cocos", "displayName": "West Island, Cocos (Keeling) Islands" },
        "the valley": { "timezone": "America/Anguilla", "displayName": "The Valley, Anguilla" },
        "saint helier": { "timezone": "Europe/Jersey", "displayName": "Saint Helier, Jersey" },
        "douglas": { "timezone": "Europe/Isle_of_Man", "displayName": "Douglas, Isle of Man" },
        "saint peter port": { "timezone": "Europe/Guernsey", "displayName": "Saint Peter Port, Guernsey" },
        "brades": { "timezone": "America/Montserrat", "displayName": "Brades, Montserrat" },
        "cockburn town": { "timezone": "America/Grand_Turk", "displayName": "Cockburn Town, Turks and Caicos Islands" },
        "gibraltar": { "timezone": "Europe/Gibraltar", "displayName": "Gibraltar, Gibraltar" },
        "saint pierre": { "timezone": "America/Miquelon", "displayName": "Saint-Pierre, Saint Pierre and Miquelon" },
        "mamoudzou": { "timezone": "Indian/Mayotte", "displayName": "Mamoudzou, Mayotte" },
        "saint-denis": { "timezone": "Indian/Reunion", "displayName": "Saint-Denis, Reunion" },
        "gustavia": { "timezone": "America/St_Barthelemy", "displayName": "Gustavia, Saint Barthélemy" },
        "marigot": { "timezone": "America/St_Martin", "displayName": "Marigot, Saint Martin" },
        "torshavn": { "timezone": "Atlantic/Faroe", "displayName": "Tórshavn, Faroe Islands" },
        "mariehamn": { "timezone": "Europe/Mariehamn", "displayName": "Mariehamn, Åland Islands" },
        "george town (ascension)": { "timezone": "Atlantic/Ascension", "displayName": "George Town, Ascension Island" },
        "ramallah": { "timezone": "Asia/Jerusalem", "displayName": "Ramallah, Palestine" },
        "gaza": { "timezone": "Asia/Gaza", "displayName": "Gaza, Palestine" },
        "cluj-napoca": { "timezone": "Europe/Bucharest", "displayName": "Cluj-Napoca, Romania" },
        "brasov": { "timezone": "Europe/Bucharest", "displayName": "Brașov, Romania" },
        "sibiu": { "timezone": "Europe/Bucharest", "displayName": "Sibiu, Romania" },
        "Nice": { "timezone": "Europe/Paris", "displayName": "Nice, France" },
    };